email:
  maximum: 255
micropost:
  accept_for_style_image: "image/jpeg,image/gif,image/png"
  maximum_megabytes: 5
  maximum_length_content: 140
  size_for_gravatar: 50
password:
  minimum: 6
user:
  reset_expired_time: 2
  size: 80
  size_gravatar_for: 50
  users_per_page: 10
username:
  maximum: 50
